// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmkwldkBm_WcUu7d9hm5JJpRkex19B4g',
    appId: '1:371629161867:web:71a5abc7f902286ebdc38e',
    messagingSenderId: '371629161867',
    projectId: 'applications-web2-tp1-equipe',
    authDomain: 'applications-web2-tp1-equipe.firebaseapp.com',
    storageBucket: 'applications-web2-tp1-equipe.appspot.com',
    measurementId: 'G-64EP2DDNV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAanpFaxqoM1SmYvPG2kWFEjt8bPkZbdbU',
    appId: '1:371629161867:android:81a4763d1648120ebdc38e',
    messagingSenderId: '371629161867',
    projectId: 'applications-web2-tp1-equipe',
    storageBucket: 'applications-web2-tp1-equipe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxAiBVpA1avbAJUK0QSpCXVcLC4ALY1g',
    appId: '1:371629161867:ios:a7ae3ea2fafa6fcbbdc38e',
    messagingSenderId: '371629161867',
    projectId: 'applications-web2-tp1-equipe',
    storageBucket: 'applications-web2-tp1-equipe.appspot.com',
    iosClientId: '371629161867-2qk0ue03mlp0505tjn9m1iiuge4t991f.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundmood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxAiBVpA1avbAJUK0QSpCXVcLC4ALY1g',
    appId: '1:371629161867:ios:a7ae3ea2fafa6fcbbdc38e',
    messagingSenderId: '371629161867',
    projectId: 'applications-web2-tp1-equipe',
    storageBucket: 'applications-web2-tp1-equipe.appspot.com',
    iosClientId: '371629161867-2qk0ue03mlp0505tjn9m1iiuge4t991f.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundmood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd0uglKGEARgbPDshKFHbd29RTNcL66VU',
    appId: '1:371629161867:web:c8d4f3f9eb4845c2bdc38e',
    messagingSenderId: '371629161867',
    projectId: 'applications-web2-tp1-equipe',
    authDomain: 'applications-web2-tp1-equipe.firebaseapp.com',
    storageBucket: 'applications-web2-tp1-equipe.appspot.com',
    measurementId: 'G-L65V6BHNG4',
  );
}
